using TMPro;
using UnityEngine;

public class UiCoinCounter : MonoBehaviour
{
    [SerializeField] private TextMeshProUGUI coinsText;
    [SerializeField] private CoinsDataSo coinsData;

    private void OnEnable()
    {
        PickablesController.onCoinsPicked += OnCoinsChanged_WriteCoins;
        PlayerController.onPlayerDie += OnPlayerDie_RestartCoins;
    }

    private void Start()
    {
        coinsData.coins = 0;
        coinsText.text = coinsData.coins.ToString("0");
    }

    private void OnDisable()
    {
        PickablesController.onCoinsPicked -= OnCoinsChanged_WriteCoins;
        PlayerController.onPlayerDie -= OnPlayerDie_RestartCoins;
    }

    public void OnCoinsChanged_WriteCoins(PickablesController pickablesController)
    {
        coinsData.coins++;
        coinsText.text = coinsData.coins.ToString("0");
    }

    public void OnPlayerDie_RestartCoins(PlayerController playerController)
    {
        coinsData.coins = 0;
    }
}
